# Generated by Django 6.0 on 2026-01-12 15:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('pdf_file', models.FileField(upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='فایل PDF')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='تصویر جلد')),
                ('page_count', models.PositiveIntegerField(default=0, verbose_name='تعداد صفحات')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='حجم فایل')),
                ('processing_status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت پردازش')),
                ('processing_error', models.TextField(blank=True, verbose_name='خطای پردازش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='آپلود شده توسط')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(verbose_name='شماره صفحه')),
                ('image', models.ImageField(upload_to='pages/', verbose_name='تصویر صفحه')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='page_thumbnails/', verbose_name='تامبنیل')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='عرض')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='ارتفاع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='books.book', verbose_name='کتاب')),
            ],
            options={
                'verbose_name': 'صفحه کتاب',
                'verbose_name_plural': 'صفحات کتاب',
                'ordering': ['book', 'page_number'],
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page', models.PositiveIntegerField(default=1, verbose_name='صفحه فعلی')),
                ('last_read_at', models.DateTimeField(auto_now=True, verbose_name='آخرین مطالعه')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='books.book', verbose_name='کتاب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیشرفت مطالعه',
                'verbose_name_plural': 'پیشرفت\u200cهای مطالعه',
            },
        ),
        migrations.CreateModel(
            name='UserBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(verbose_name='شماره صفحه')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='books.book', verbose_name='کتاب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بوکمارک',
                'verbose_name_plural': 'بوکمارک\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['processing_status'], name='books_book_process_95fb67_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['created_at'], name='books_book_created_572b47_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='books_book_title_d3218d_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='books_book_uploade_716516_idx'),
        ),
        migrations.AddIndex(
            model_name='bookpage',
            index=models.Index(fields=['book', 'page_number'], name='books_bookp_book_id_83016b_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookpage',
            constraint=models.UniqueConstraint(fields=('book', 'page_number'), name='unique_book_page'),
        ),
        migrations.AlterUniqueTogether(
            name='readingprogress',
            unique_together={('user', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='userbookmark',
            unique_together={('user', 'book', 'page_number')},
        ),
    ]
